LineLength:
  Max: 90

Metrics/MethodLength:
  Max: 16

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'test/**'

Lint/UnneededCopDisableDirective:
  Exclude:
    - 'test/**'

